package vn.printgo.model;
// Generated Jan 8, 2020 11:27:41 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpFile generated by hbm2java
 */
@Entity(name = "tmp_file")
@Table(name = "tmp_file", catalog = "printgo_crm")
public class TmpFile implements java.io.Serializable {

	private static final long serialVersionUID = -2919860116141815380L;
	private Integer id;
	private String name;
	private String nameMd;
	private String path;
	private Date inTime;
	private Date updateTime;

	public TmpFile() {
	}

	public TmpFile(Date updateTime) {
		this.updateTime = updateTime;
	}

	public TmpFile(String name, String nameMd, String path, Date inTime, Date updateTime) {
		this.name = name;
		this.nameMd = nameMd;
		this.path = path;
		this.inTime = inTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name_md", length = 100)
	public String getNameMd() {
		return this.nameMd;
	}

	public void setNameMd(String nameMd) {
		this.nameMd = nameMd;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "in_time", length = 19)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
