package vn.printgo.model;
// Generated Oct 18, 2019 9:57:19 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserPermision generated by hbm2java
 */
@Entity
@Table(name = "user_permision", catalog = "printgo")
public class UserPermision implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String action;
	private String roles;

	public UserPermision() {
	}

	public UserPermision(String action, String roles) {
		this.action = action;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "action", nullable = false, length = 100)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "roles", nullable = false)
	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

}
