package vn.printgo.model;
// Generated Oct 18, 2019 9:57:19 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "printgo", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class UserProfile implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String type;
	private Set<User> users = new HashSet<User>(0);

	public UserProfile() {
	}

	public UserProfile(String type) {
		this.type = type;
	}

	public UserProfile(String type, Set<User> users) {
		this.type = type;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", unique = true, nullable = false, length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_link_profile", catalog = "printgo", joinColumns = {
			@JoinColumn(name = "user_profile_id", nullable = false, updatable = false) }, inverseJoinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
